
server:
  port: 8001
  servlet:
    context-path: /details

dubbo:
  application:
    name: boot-details
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    port: 20881


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/17_shop?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver